config/routes.rb
Rails.application.routes.draw do
  resources :periods
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloquear', registration: 'registrar', sign_up: 'cadastrar' }
  
  post '/student_lessons/new' #É Necessário para manter a /student_lessons/registrar funcionando

  root 'pages#home'
  get 'pages/home'
  get 'pages/homeadmin'
  get 'pages/homestandard'
  get 'pages/homeprofessor'
  get 'pages/homedirector'

  scope path_names: {new: 'registrar', edit: 'editar'} do
    resources :users
    resources :student_lessons
    resources :student_classrooms
    resources :subject_courses
    resources :classrooms
    resources :lessons
    resources :students
    resources :teachers
    resources :subjects
    resources :courses
    resources :departments
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.standard?
      can :read, :all
      can :destroy, User, id: user.id 
      can :update, User, id: user.id
    end

    if user.admin?
      can :manage, :all
    end

    if user.professor?
      can :read, :all
      can :destroy, User, id: user.id
      can :update, User, id: user.id
      can [:create, :update, :destroy, :read], Lesson
      can :create, StudentLesson
    end

    if user.director?
      can [:create, :update, :destroy, :read], Department
      can [:create, :update, :destroy, :read], Subject
      can [:create, :update, :destroy, :read], Classroom
      can [:update, :read], Teacher
      can [:update, :read], Student
      can :read, :all
      can :create, StudentClassroom
      can :create, SubjectCourse
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :period
  belongs_to :teacher
  belongs_to :subject
  has_many :lessons
  has_many :student_classrooms
  has_many :students, through: :student_classrooms

  validates :number, presence: true, numericality: { only_integer: true }
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students

  has_many :subject_courses
  has_many :subjects, through: :subject_courses


  validates :name, presence: true, uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers

    validates :name, presence: true, uniqueness: true
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
    belongs_to :subject
    belongs_to :discipline, class_name: "Subject"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom

  has_many :student_lessons
  has_many :students, through: :student_lessons

  #accepts_nested_attributes_for :student_lessons

  validates :duration, presence: true, numericality: { only_integer: true }
  
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms

    validates :number, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course

  has_many :student_classrooms
  has_many :classrooms, through: :student_classrooms

  has_many :student_lessons
  has_many :lessons, through: :student_lessons


  validates :name, presence: true
  validates :registration, presence: true, numericality: true
end

app/models/student_lesson.rb
class StudentLesson < ApplicationRecord
  belongs_to :student
  belongs_to :lesson

  validates :student_id, presence: true, uniqueness: {:scope => :lesson_id}
  validates :lesson_id, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true
  has_many :classrooms

  has_many :subject_courses
  has_many :courses, through: :subject_courses

  #SELF RELATION
  has_many :equivalences
  has_many :disciplines, through: :equivalences, source: :discipline


  validates :name, presence: true
  validates :workload, presence: true, numericality: { only_integer: true }
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :course
  belongs_to :subject

  validates :subject_id, presence: true, uniqueness: {:scope => :course_id}
  validates :course_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_one :teacher

  validates :name, :photo, :password_confirmation, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  enum kind: {
    standard: 0,
    admin: 1,
    professor: 2,
    director: 3
  }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @classrooms = Classroom.all #Utilizado para colocar Aluno em uma turma
  end

  # GET /students/new
  def new
    @courses = Course.all
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @courses = Course.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @courses = Course.all

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :registration, :course_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.select :course_id, @courses.collect { |course| [course.name, course.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.registration %></td>
        <td><%= student.course.name %></td>

        <% if can? :read, student %>
          <td><%= link_to 'Show', student %></td>
        <% end %>
        <% if can? :update, student %>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <% end %>
        <% if can? :destroy, student %>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Student %>
  <%= link_to 'New Student', new_student_path %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @student.registration %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course.name %>
</p>

<p>
  <strong>Turmas: </strong>
  <ul>
    <% @student.classrooms.each do |classroom| %>
      <li><%= classroom.number %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Aulas: </strong>
    <ul>
    <% @student.lessons.each do |lesson| %>
      <li><%= lesson.time %></li>
    <% end %>
  </ul>
</p>

<% if can? :update, @student %>
  <%= link_to 'Edit', edit_student_path(@student) %> |
<% end %>

<%= link_to 'Back', students_path %>