config/routes.rb
Rails.application.routes.draw do
  resources :periods
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloquear', registration: 'registrar', sign_up: 'cadastrar' }
  
  post '/student_lessons/new' #É Necessário para manter a /student_lessons/registrar funcionando

  root 'pages#home'
  get 'pages/home'
  get 'pages/homeadmin'
  get 'pages/homestandard'
  get 'pages/homeprofessor'
  get 'pages/homedirector'

  scope path_names: {new: 'registrar', edit: 'editar'} do
    resources :users
    resources :student_lessons
    resources :student_classrooms
    resources :subject_courses
    resources :classrooms
    resources :lessons
    resources :students
    resources :teachers
    resources :subjects
    resources :courses
    resources :departments
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.standard?
      can :read, :all
      can :destroy, User, id: user.id 
      can :update, User, id: user.id
    end

    if user.admin?
      can :manage, :all
    end

    if user.professor?
      can :read, :all
      can :destroy, User, id: user.id
      can :update, User, id: user.id
      can [:create, :update, :destroy, :read], Lesson
      can :create, StudentLesson
    end

    if user.director?
      can [:create, :update, :destroy, :read], Department
      can [:create, :update, :destroy, :read], Subject
      can [:create, :update, :destroy, :read], Classroom
      can [:update, :read], Teacher
      can [:update, :read], Student
      can :read, :all
      can :create, StudentClassroom
      can :create, SubjectCourse
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :period
  belongs_to :teacher
  belongs_to :subject
  has_many :lessons
  has_many :student_classrooms
  has_many :students, through: :student_classrooms

  validates :number, presence: true, numericality: { only_integer: true }
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students

  has_many :subject_courses
  has_many :subjects, through: :subject_courses


  validates :name, presence: true, uniqueness: true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers

    validates :name, presence: true, uniqueness: true
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
    belongs_to :subject
    belongs_to :discipline, class_name: "Subject"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom

  has_many :student_lessons
  has_many :students, through: :student_lessons

  #accepts_nested_attributes_for :student_lessons

  validates :duration, presence: true, numericality: { only_integer: true }
  
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms

    validates :number, presence: true, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course

  has_many :student_classrooms
  has_many :classrooms, through: :student_classrooms

  has_many :student_lessons
  has_many :lessons, through: :student_lessons


  validates :name, presence: true
  validates :registration, presence: true, numericality: true
end

app/models/student_lesson.rb
class StudentLesson < ApplicationRecord
  belongs_to :student
  belongs_to :lesson

  validates :student_id, presence: true, uniqueness: {:scope => :lesson_id}
  validates :lesson_id, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true
  has_many :classrooms

  has_many :subject_courses
  has_many :courses, through: :subject_courses

  #SELF RELATION
  has_many :equivalences
  has_many :disciplines, through: :equivalences, source: :discipline


  validates :name, presence: true
  validates :workload, presence: true, numericality: { only_integer: true }
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :course
  belongs_to :subject

  validates :subject_id, presence: true, uniqueness: {:scope => :course_id}
  validates :course_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_one :teacher

  validates :name, :photo, :password_confirmation, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  enum kind: {
    standard: 0,
    admin: 1,
    professor: 2,
    director: 3
  }
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :set_students, only: [:new, :edit]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @classrooms = Classroom.all
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
    @classrooms = Classroom.all
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @classrooms = Classroom.all

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:time, :duration, :classroom_id, student_lessons_attributes: [:student_id, :lesson_id, :presence])
    end

    def set_students
      @students = Student.all
    end

  end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :classroom_id %>
    <%= form.select :classroom_id, @classrooms.collect { |classroom| [classroom.number, classroom.id] } %>
  </div>

<!--
  <div class="field">
    <%= form.fields_for :student_lessons do |student_lessons_field| %>
      <div>
        <% @students.each do |student| %>
          <%= student.name %>
          <%= student_lessons_field.hidden_field :student_id, value: student.id %>
          <%= student_lessons_field.check_box :presence %>
        <% end %>
      </div>
    <% end %>
  </div>
-->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Duration</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.time %></td>
        <td><%= lesson.duration %></td>
        <td><%= lesson.classroom.number %></td>

        <% if can? :read, lesson %>
          <td><%= link_to 'Show', lesson %></td>
        <% end %>
        <% if can? :update, lesson %>
          <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <% end %>
        <% if can? :destroy, lesson %>
          <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Lesson %>
  <%= link_to 'New Lesson', new_lesson_path %>
<% end %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @lesson.time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lesson.duration %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @lesson.classroom.number %>
</p>

<p>
  <strong>Alunos Presentes:</strong>
  <ul>
    <% @lesson.students.each do |student| %>
      <li><%= student.name %></li>
    <% end %>
  </ul>
</p>

<% if can? :create, StudentLesson %>
  <%= link_to 'Fazer Chamada', new_student_lesson_path %>
<% end %>

<% if can? :update, @lesson %>
  <%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<% end %>

<%= link_to 'Back', lessons_path %>